SHELL = /bin/sh
CC = gcc
CFLAGS = -O2 -g -fPIC
LIBNAME = libasgp1.so
OBJFILES = llist.o stack.o queue.o heap.o union_find.o

library: $(OBJFILES)
    $(CC) -shared -o libasgp1.so $(OBJFILES)

stack.o queue.o : llist.h